### ISSUE TITLE
Major: Error Tracking and Reporting

### ISSUE THREAD

**Issue by jimmybisenius** [logmeals/jims-calorie-counter#41]
- [ ] An error log to track all ongoing errors
- [ ] Error listeners on barcode scanning, cloud ai, and open ai
- [ ] Automatic error reporting
- [ ] A screen to view all errors
- [ ] Automatic error reporting toggle button
- [ ] Manual bug report
- [ ] Freeform bug report
